# Generated by Django 6.0.1 on 2026-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_bottle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom per-bottle price for this customer; falls back to the standard price when empty', max_digits=10, null=True),
        ),
    ]
