# Generated by Django 5.2.4 on 2026-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_custom_bottle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Running balance: positive = customer has credit, negative = customer owes', max_digits=12),
        ),
    ]
