# Generated by Django 5.2.4 on 2026-06-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mobileprofileconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all', 'Everyone'), ('customers', 'Customers Only'), ('riders', 'Delivery Boys Only'), ('admins', 'Admins Only'), ('test', 'Test Mode')], default='all', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0, help_text='Number of devices that received the notification')),
                ('total_devices', models.IntegerField(default=0, help_text='Total number of target devices')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When notification is scheduled to be sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was actually sent', null=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label for this template', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all', 'Everyone'), ('customers', 'Customers Only'), ('riders', 'Delivery Boys Only'), ('admins', 'Admins Only'), ('test', 'Test Mode')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
