# Generated by Django 6.0.1 on 2026-08-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notificationhistory_notificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portion',
            field=models.CharField(blank=True, help_text='Ground floor / 1st floor / etc. — optional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full delivery address; kept in sync with the structured parts below', null=True),
        ),
    ]
