# Generated by Django 6.0.1 on 2026-08-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_block_area_userprofile_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, help_text='Short account code shown on ledger statements, e.g. 00245. Assigned automatically on first use.', max_length=12, null=True, unique=True),
        ),
    ]
