# Generated by Django 6.0.1 on 2026-08-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the signup dropdown.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='block_area',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, help_text='Locality, e.g. Johar Town. Suggested from the Area list, but a customer may enter their own.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block',
            field=models.CharField(blank=True, help_text='Block or street within the area — optional', max_length=100, null=True),
        ),
    ]
