# Generated by Django 6.0.1 on 2026-08-02 22:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_area_remove_userprofile_block_area_userprofile_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_enabled', models.BooleanField(default=True, help_text='Master switch. Off means the app stops reporting entirely.')),
                ('tracking_mode', models.CharField(choices=[('always', 'Always — 24/7, even with the app closed'), ('active_delivery', 'Only while a delivery is in progress'), ('foreground', 'Only while the app is open')], default='always', help_text="'always' is the deliberate business default: riders are tracked around the clock, not only on shift.", max_length=20)),
                ('ping_interval_seconds', models.PositiveIntegerField(default=60, help_text='Seconds between location reports.')),
                ('ping_distance_meters', models.PositiveIntegerField(default=50, help_text='Report early if the rider has moved at least this far.')),
                ('trail_retention_days', models.PositiveIntegerField(default=7, help_text='How long the breadcrumb trail is kept; prune_rider_pings deletes anything older.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking Settings',
                'verbose_name_plural': 'Tracking Settings',
            },
        ),
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('accuracy_m', models.FloatField(blank=True, help_text='Reported horizontal accuracy in metres.', null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, help_text='Degrees clockwise from true north.', null=True)),
                ('battery_level', models.SmallIntegerField(blank=True, help_text='Device battery percentage, when the app reports it.', null=True)),
                ('is_moving', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(limit_choices_to={'profile__user_type': 'delivery_boy'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Location',
                'verbose_name_plural': 'Rider Locations',
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='rider_location_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='rider_location_longitude_range')],
            },
        ),
        migrations.CreateModel(
            name='RiderLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(limit_choices_to={'profile__user_type': 'delivery_boy'}, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Location Ping',
                'verbose_name_plural': 'Rider Location Pings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['rider', '-recorded_at'], name='rider_ping_recent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='rider_ping_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='rider_ping_longitude_range')],
            },
        ),
    ]
