# Generated by Django 6.0.1 on 2026-08-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_trackingsettings_riderlocation_riderlocationping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount per unit'), ('percentage', 'Percentage of the line')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text="Rupees off per unit for 'fixed'; percent of the line gross for 'percentage' (at most 100).", max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop discounting future bills; history keeps its frozen snapshots either way.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Category',
                'verbose_name_plural': 'Discount Categories',
                'ordering': ['name'],
                'permissions': [('can_override_discount', 'Can override the auto-applied discount at billing')],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discount_category',
            field=models.ForeignKey(blank=True, help_text="Discount tier applied automatically whenever this customer is billed. PROTECT: a category in use cannot be deleted, only reassigned or deactivated. Never exposed to the customer's own API surface.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounts.discountcategory'),
        ),
    ]
