# Generated by Django 6.0.1 on 2026-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='portion',
            field=models.CharField(blank=True, choices=[('ground', 'Ground'), ('upper', 'Upper'), ('lower', 'Lower'), ('first_floor', '1st Floor'), ('second_floor', '2nd Floor'), ('basement', 'Basement')], help_text="Which part of the house — optional. A fixed list, so the field can be grouped and reported on instead of arriving as 'Ground', 'ground floor', 'GF' and 'g'.", max_length=50, null=True),
        ),
    ]
