# Generated by Django 6.0.1 on 2026-08-04 09:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_normalize_portion_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('other', 'Other')], default='home', max_length=20)),
                ('custom_label', models.CharField(blank=True, default='', help_text="Used instead of the label when label is 'other'.", max_length=50)),
                ('house_number', models.CharField(blank=True, default='', max_length=50)),
                ('portion', models.CharField(blank=True, choices=[('ground', 'Ground'), ('upper', 'Upper'), ('lower', 'Lower'), ('first_floor', '1st Floor'), ('second_floor', '2nd Floor'), ('basement', 'Basement')], default='', max_length=50)),
                ('block', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='', help_text='Composed from the parts on save; what riders and PDFs read.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('is_default', models.BooleanField(default=False, help_text='The address checkout pre-selects. Exactly one per customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer addresses',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='accounts_cu_user_id_41ae9e_idx')],
            },
        ),
    ]
