# Generated by Django 6.0.1 on 2026-08-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_seed_address_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_place_label',
            field=models.CharField(blank=True, default='', help_text="Name used when this work place's location is shared outside the app. Falls back to the business name when empty.", max_length=120),
        ),
    ]
