# Generated by Django 5.2.4 on 2026-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_number',
            field=models.CharField(blank=True, help_text='Mobile number for JazzCash/EasyPaisa', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa')], default='COD', max_length=50),
        ),
    ]
