# Generated by Django 5.2.4 on 2026-02-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_current_location_and_more'),
        ('orders', '0002_order_is_paid_order_payment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_boy',
            field=models.ForeignKey(blank=True, help_text='Delivery boy assigned to this order', limit_choices_to={'user_type': 'delivery_boy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
