# Generated by Django 5.2.4 on 2026-02-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_assigned_delivery_boy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of cash received', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_received',
            field=models.BooleanField(default=False, help_text='Whether cash was received from customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Responding', 'Not Responding'), ('Not Needed', 'Not Needed'), ('Pending', 'Pending')], default='Pending', help_text='Delivery completion status', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_bottles',
            field=models.PositiveIntegerField(default=0, help_text='Number of bottles delivered'),
        ),
    ]
