# Generated by Django 5.2.4 on 2026-02-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cash_amount_order_cash_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status name (e.g., Delivered, Not Responding)', max_length=50, unique=True)),
                ('color', models.CharField(default='#007AFF', help_text='Hex color code (e.g., #2ecc71)', max_length=7)),
                ('background_color', models.CharField(default='#f0f8ff', help_text='Background hex color', max_length=7)),
                ('border_color', models.CharField(default='#007AFF', help_text='Border hex color', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this status is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Status',
                'verbose_name_plural': 'Delivery Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, default='Pending', help_text='Delivery completion status - managed via DeliveryStatus model', max_length=50),
        ),
    ]
