# Generated by Django 5.2.4 on 2026-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverystatus_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when delivery status was first updated from Pending', null=True),
        ),
    ]
