# Generated by Django 6.0.1 on 2026-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_guest_name_order_guest_phone_order_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_number',
            field=models.CharField(blank=True, help_text='Legacy field from when mobile wallets were accepted; unused now that the business is cash-only.', max_length=20, null=True),
        ),
    ]
