# Generated by Django 6.0.1 on 2026-08-03 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_discount_amount_order_discount_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_note',
            field=models.TextField(blank=True, default='', help_text="Staff instruction for the assigned rider ('gate code 4412', 'collect old dues'). Never shown to the customer, and the rider can read but not write it."),
        ),
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('no_need', 'No need today'), ('no_response', 'No response at the door')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Visit',
                'verbose_name_plural': 'Customer Visits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='visit_customer_recent_idx')],
            },
        ),
    ]
