# Generated by Django 6.0.1 on 2026-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_area_order_block_order_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='portion',
            field=models.CharField(blank=True, choices=[('ground', 'Ground'), ('upper', 'Upper'), ('lower', 'Lower'), ('first_floor', '1st Floor'), ('second_floor', '2nd Floor'), ('basement', 'Basement')], default='', max_length=50),
        ),
    ]
