# Generated by Django 6.0.1 on 2026-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_label',
            field=models.CharField(blank=True, default='', help_text='Which address book entry this came from (Home, Office…).', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
