# Generated by Django 6.0.1 on 2026-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from the storefront and the product form. Products already in this category keep it.'),
        ),
    ]
