"""Default localization data, shared by the seeder management command and the
standalone seed_translations.py script. Edit translations here only."""

# category name -> list of {slug, text_en, text_ur}
TRANSLATIONS = {
    'Profile Screen': [
        {'slug': 'personal_info', 'text_en': 'Personal Information', 'text_ur': 'ذاتی معلومات'},
        {'slug': 'first_name', 'text_en': 'First Name', 'text_ur': 'پہلا نام'},
        {'slug': 'last_name', 'text_en': 'Last Name', 'text_ur': 'آخری نام'},
        {'slug': 'save_changes', 'text_en': 'Save Changes', 'text_ur': 'تبدیلیاں محفوظ کریں'},
        {'slug': 'support_complaints', 'text_en': 'Support & Complaints', 'text_ur': 'مدد اور شکایات'},
        {'slug': 'logout', 'text_en': 'Logout', 'text_ur': 'لاگ آؤٹ'},
    ],
    'Home Screen': [
        {'slug': 'latest_products', 'text_en': 'Latest Products', 'text_ur': 'تازہ ترین مصنوعات'},
        {'slug': 'search_placeholder', 'text_en': 'Search products...', 'text_ur': 'مصنوعات تلاش کریں...'},
        {'slug': 'category_all', 'text_en': 'All', 'text_ur': 'سب'},
        {'slug': 'no_products_found', 'text_en': 'No products found.', 'text_ur': 'کوئی مصنوعات نہیں ملیں۔'},
        {'slug': 'tap_retry', 'text_en': 'Tap to retry', 'text_ur': 'دوبارہ کوشش کرنے کے لیے تھپتھپائیں'},
    ],
    'Order History Screen': [
        {'slug': 'my_orders', 'text_en': 'My Orders', 'text_ur': 'میرے آرڈرز'},
        {'slug': 'order_number', 'text_en': 'Order #', 'text_ur': 'آرڈر نمبر'},
        {'slug': 'total_amount', 'text_en': 'Total Amount', 'text_ur': 'کل رقم'},
        {'slug': 'no_orders', 'text_en': 'No orders found', 'text_ur': 'کوئی آرڈر نہیں ملا'},
        {'slug': 'start_shopping', 'text_en': 'Start Shopping', 'text_ur': 'خریداری شروع کریں'},
        {'slug': 'unknown_product', 'text_en': 'Unknown Product', 'text_ur': 'نامعلوم مصنوعات'},
        {'slug': 'status_pending', 'text_en': 'Pending', 'text_ur': 'زیر التواء'},
        {'slug': 'status_processing', 'text_en': 'Processing', 'text_ur': 'عمل جاری ہے'},
        {'slug': 'status_shipped', 'text_en': 'Shipped', 'text_ur': 'بھیج دیا گیا'},
        {'slug': 'status_delivered', 'text_en': 'Delivered', 'text_ur': 'پہنچایا گیا'},
        {'slug': 'status_cancelled', 'text_en': 'Cancelled', 'text_ur': 'منسوخ شدہ'},
    ],
    'Cart Screen': [
        {'slug': 'your_cart_empty', 'text_en': 'Your cart is empty', 'text_ur': 'آپ کی ٹوکری خالی ہے'},
        {'slug': 'cart_total', 'text_en': 'Total:', 'text_ur': 'کل:'},
        {'slug': 'checkout_btn', 'text_en': 'Checkout', 'text_ur': 'چیک آؤٹ'},
        {'slug': 'no_img', 'text_en': 'No Img', 'text_ur': 'کوئی تصویر نہیں'},
    ],
    'Checkout Screen': [
        {'slug': 'checkout_title', 'text_en': 'Checkout', 'text_ur': 'چیک آؤٹ'},
        {'slug': 'order_summary', 'text_en': 'Order Summary', 'text_ur': 'آرڈر کا خلاصہ'},
        {'slug': 'shipping_address', 'text_en': 'Shipping Address', 'text_ur': 'شپنگ ایڈریس'},
        {'slug': 'enter_address_placeholder', 'text_en': 'Enter your full address', 'text_ur': 'اپنا مکمل پتہ درج کریں'},
        {'slug': 'payment_method', 'text_en': 'Payment Method', 'text_ur': 'ادائیگی کا طریقہ'},
        {'slug': 'cod_label', 'text_en': 'Cash on Delivery', 'text_ur': 'کیش آن ڈیلیوری'},
        {'slug': 'mobile_number_label', 'text_en': 'Mobile Number', 'text_ur': 'موبائل نمبر'},
        {'slug': 'mobile_placeholder', 'text_en': '03XXXXXXXXX', 'text_ur': '03XXXXXXXXX'},
        {'slug': 'place_order', 'text_en': 'Place Order', 'text_ur': 'آرڈر کریں'},
        {'slug': 'pay_via', 'text_en': 'Pay via', 'text_ur': 'کے ذریعے ادائیگی کریں'},
        {'slug': 'error_address', 'text_en': 'Please enter a shipping address', 'text_ur': 'براہ کرم شپنگ ایڈریس درج کریں'},
        {'slug': 'error_cart_empty', 'text_en': 'Your cart is empty', 'text_ur': 'آپ کی ٹوکری خالی ہے'},
        {'slug': 'success_order', 'text_en': 'Your order has been placed successfully!', 'text_ur': 'آپ کا آرڈر کامیابی سے دے دیا گیا ہے!'},
        {'slug': 'error_payment_number', 'text_en': 'Please enter your {paymentMethod} mobile number', 'text_ur': 'براہ کرم اپنا {paymentMethod} موبائل نمبر درج کریں'},
        {'slug': 'success_payment_request', 'text_en': 'Payment request sent to {mobileNumber}. Please approve the transaction on your phone.', 'text_ur': 'ادائیگی کی درخواست {mobileNumber} پر بھیجی گئی۔ براہ کرم اپنے فون پر ٹرانزیکشن کی منظوری دیں۔'},
        {'slug': 'payment_helper_text', 'text_en': 'Please enter your {paymentMethod} account number. You will receive a prompt to approve the payment.', 'text_ur': 'براہ کرم اپنا {paymentMethod} اکاؤنٹ نمبر درج کریں۔ آپ کو ادائیگی کی منظوری کا اشارہ موصول ہوگا۔'},
    ],
    'Product Detail Screen': [
        {'slug': 'in_stock', 'text_en': 'In Stock', 'text_ur': 'دستیاب ہے'},
        {'slug': 'out_of_stock', 'text_en': 'Out of Stock', 'text_ur': 'دستیاب نہیں ہے'},
        {'slug': 'description_title', 'text_en': 'Description', 'text_ur': 'تفصیل'},
        {'slug': 'no_description', 'text_en': 'No description available for this product.', 'text_ur': 'اس مصنوعات کے لیے کوئی تفصیل دستیاب نہیں ہے۔'},
        {'slug': 'add_to_cart', 'text_en': 'Add to Cart', 'text_ur': 'ٹوکری میں شامل کریں'},
        {'slug': 'added_to_cart_success', 'text_en': 'Added to cart!', 'text_ur': 'ٹوکری میں شامل کر دیا گیا!'},
        {'slug': 'keep_shopping', 'text_en': 'Keep Shopping', 'text_ur': 'خریداری جاری رکھیں'},
        {'slug': 'go_to_cart', 'text_en': 'Go to Cart', 'text_ur': 'ٹوکری پر جائیں'},
        {'slug': 'success', 'text_en': 'Success', 'text_ur': 'کامیابی'},
        {'slug': 'error', 'text_en': 'Error', 'text_ur': 'خرابی'},
    ],
    'Login Screen': [
        {'slug': 'welcome_back', 'text_en': 'Welcome Back', 'text_ur': 'خوش آمدید'},
        {'slug': 'sign_in_continue', 'text_en': 'Sign in to continue', 'text_ur': 'جاری رکھنے کے لیے سائن ان کریں'},
        {'slug': 'username_label', 'text_en': 'Username', 'text_ur': 'صارف کا نام'},
        {'slug': 'username_placeholder', 'text_en': 'Enter your username', 'text_ur': 'اپنا صارف نام درج کریں'},
        {'slug': 'password_label', 'text_en': 'Password', 'text_ur': 'پاس ورڈ'},
        {'slug': 'password_placeholder', 'text_en': 'Enter your password', 'text_ur': 'اپنا پاس ورڈ درج کریں'},
        {'slug': 'login_btn', 'text_en': 'Login', 'text_ur': 'لاگ ان کریں'},
        {'slug': 'no_account_signup', 'text_en': "Don't have an account? Sign Up", 'text_ur': 'اکاؤنٹ نہیں ہے؟ سائن اپ کریں'},
        {'slug': 'fill_all_fields', 'text_en': 'Please fill in all fields', 'text_ur': 'براہ کرم تمام خانے پُر کریں'},
        {'slug': 'login_failed', 'text_en': 'Login Failed', 'text_ur': 'لاگ ان ناکام'},
    ],
    'Register Screen': [
        {'slug': 'create_account', 'text_en': 'Create Account', 'text_ur': 'اکاؤنٹ بنائیں'},
        {'slug': 'sign_up_started', 'text_en': 'Sign up to get started', 'text_ur': 'شروع کرنے کے لیے سائن اپ کریں'},
        {'slug': 'username_choose_placeholder', 'text_en': 'Choose a username', 'text_ur': 'صارف نام منتخب کریں'},
        {'slug': 'email_label', 'text_en': 'Email', 'text_ur': 'ای میل'},
        {'slug': 'email_placeholder', 'text_en': 'Enter your email', 'text_ur': 'اپنا ای میل درج کریں'},
        {'slug': 'confirm_password_label', 'text_en': 'Confirm Password', 'text_ur': 'پاس ورڈ کی تصدیق کریں'},
        {'slug': 'confirm_password_placeholder', 'text_en': 'Confirm your password', 'text_ur': 'اپنے پاس ورڈ کی تصدیق کریں'},
        {'slug': 'password_requirements', 'text_en': 'Min 8 chars, uppercase, lowercase, number, special char', 'text_ur': 'کم از کم 8 حروف، بڑے، چھوٹے، نمبر، خصوصی حرف'},
        {'slug': 'signup_btn', 'text_en': 'Sign Up', 'text_ur': 'سائن اپ کریں'},
        {'slug': 'has_account_login', 'text_en': 'Already have an account? Login', 'text_ur': 'پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں'},
        {'slug': 'passwords_mismatch', 'text_en': 'Passwords do not match', 'text_ur': 'پاس ورڈ مماثل نہیں ہیں'},
        {'slug': 'registration_failed', 'text_en': 'Registration Failed', 'text_ur': 'رجسٹریشن ناکام'},
    ],
    'Complaint Screen': [
        {'slug': 'my_complaints', 'text_en': 'My Complaints', 'text_ur': 'میری شکایات'},
        {'slug': 'new_complaint', 'text_en': 'New Complaint', 'text_ur': 'نئی شکایت'},
        {'slug': 'subject_placeholder', 'text_en': 'Subject', 'text_ur': 'موضوع'},
        {'slug': 'description_placeholder', 'text_en': 'Description', 'text_ur': 'تفصیل'},
        {'slug': 'cancel_btn', 'text_en': 'Cancel', 'text_ur': 'منسوخ کریں'},
        {'slug': 'submit_btn', 'text_en': 'Submit', 'text_ur': 'جمع کرائیں'},
        {'slug': 'no_complaints', 'text_en': 'No complaints found', 'text_ur': 'کوئی شکایت نہیں ملی'},
        {'slug': 'complaint_success', 'text_en': 'Complaint submitted successfully', 'text_ur': 'شکایت کامیابی سے جمع کرائی گئی'},
        {'slug': 'complaint_failed', 'text_en': 'Failed to submit complaint', 'text_ur': 'شکایت جمع کرانے میں ناکامی'},
        {'slug': 'fetch_complaints_failed', 'text_en': 'Failed to fetch complaints', 'text_ur': 'شکایات حاصل کرنے میں ناکامی'},
        {'slug': 'status_in_progress', 'text_en': 'In Progress', 'text_ur': 'جاری ہے'},
        {'slug': 'status_resolved', 'text_en': 'Resolved', 'text_ur': 'حل ہو گیا'},
    ],
    'Common Categories': [
        {'slug': 'category_electronics', 'text_en': 'Electronics', 'text_ur': 'الیکٹرانکس'},
        {'slug': 'category_fashion', 'text_en': 'Fashion', 'text_ur': 'فیشن'},
        {'slug': 'category_clothing', 'text_en': 'Clothing', 'text_ur': 'کپڑے'},
        {'slug': 'category_home', 'text_en': 'Home', 'text_ur': 'گھر'},
        {'slug': 'category_beauty', 'text_en': 'Beauty', 'text_ur': 'خوبصورتی'},
        {'slug': 'category_sports', 'text_en': 'Sports', 'text_ur': 'کھیل'},
        {'slug': 'category_books', 'text_en': 'Books', 'text_ur': 'کتابیں'},
        {'slug': 'category_toys', 'text_en': 'Toys', 'text_ur': 'کھلونے'},
        {'slug': 'category_groceries', 'text_en': 'Groceries', 'text_ur': 'کریانہ'},
    ],
}
