# Generated by Django 5.2.4 on 2026-06-11 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('order', 'Order'), ('rider', 'Rider'), ('customer', 'Customer'), ('user', 'User')], db_index=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=250)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='activities__categor_1b1108_idx'), models.Index(fields=['target_type', 'target_id'], name='activities__target__2cb41e_idx')],
            },
        ),
    ]
