# Generated by Django 5.2.4 on 2026-02-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique key for the translation (e.g., 'home_welcome_message')", unique=True)),
                ('text_en', models.TextField(verbose_name='English Text')),
                ('text_ur', models.TextField(blank=True, null=True, verbose_name='Urdu Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
