# Generated by Django 5.2.4 on 2026-02-01 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the page or section (e.g., 'Home Screen')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Translation Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['category', 'slug']},
        ),
        migrations.AddField(
            model_name='translation',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The page or section this translation belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='localization.translationcategory'),
        ),
    ]
