# Generated by Django 6.0.1 on 2026-06-05 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('house', models.CharField(blank=True, help_text='House name / number or address', max_length=255)),
                ('bottles', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per bottle', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: bottles × unit price', max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_records_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Optional link to a registered customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Record',
                'verbose_name_plural': 'Delivery Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
