# Generated by Django 6.0.1 on 2026-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Default per-bottle price used when no customer override exists', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant Settings',
                'verbose_name_plural': 'Plant Settings',
            },
        ),
    ]
