# Generated by Django 6.0.1 on 2026-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_bottletype_deliveryrecord_bottle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually received from the customer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='paid',
            field=models.BooleanField(default=False, help_text='True when fully paid'),
        ),
    ]
