# Generated by Django 6.0.1 on 2026-06-06 09:54

from django.db import migrations
from django.db.models import F


def backfill(apps, schema_editor):
    """Existing records marked paid=True were fully paid → set received = amount."""
    DeliveryRecord = apps.get_model('plant', 'DeliveryRecord')
    DeliveryRecord.objects.filter(paid=True).update(paid_amount=F('amount'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_deliveryrecord_paid_amount_alter_deliveryrecord_paid'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
