# Generated by Django 6.0.1 on 2026-08-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_backfill_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='empties_collected',
            field=models.PositiveIntegerField(default=0, help_text='Empty bottles taken back on this visit. Usually equals the number delivered; the difference is what the customer still holds.'),
        ),
    ]
