# Generated by Django 6.0.1 on 2026-08-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_discountcategory_userprofile_discount_category'),
        ('plant', '0007_deliveryrecord_empties_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='discount_category',
            field=models.ForeignKey(blank=True, help_text='Reporting link only — the snapshot fields are what billing froze.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_records', to='accounts.discountcategory'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='discount_category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='discount_overridden',
            field=models.BooleanField(default=False, help_text='True when staff with can_override_discount pinned an explicit amount; save() then stops recomputing it.'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='discount_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: bottles × unit price before discount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated NET: bottles × unit price − discount', max_digits=12),
        ),
    ]
