# Generated by Django 6.0.1 on 2026-08-02 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_order_guest_name_order_guest_phone_order_is_hidden_and_more'),
        ('plant', '0007_deliveryrecord_empties_collected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Century Sip', max_length=150)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ledger/')),
                ('receipt_footer', models.CharField(blank=True, default='Thank you for your business.', max_length=255)),
                ('ledger_start_date', models.DateField(blank=True, help_text='Orders and deliveries dated before this are never auto-charged. Set by ledger_backfill; prevents editing an old record from silently posting a large historical charge.', null=True)),
                ('auto_charge_enabled', models.BooleanField(default=False, help_text='Master switch for automatic charges from orders and bottle deliveries. Turn off to stop the ledger moving on its own.')),
            ],
            options={
                'verbose_name': 'Ledger settings',
                'verbose_name_plural': 'Ledger settings',
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField(default=0, help_text='0 = never resets.')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Number sequence',
                'verbose_name_plural': 'Number sequences',
                'constraints': [models.UniqueConstraint(fields=('key', 'year'), name='ledger_sequence_key_year')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Value date — the day the money moved, which may predate created_at.')),
                ('entry_type', models.CharField(choices=[('opening', 'Opening Balance'), ('order_charge', 'Order Charge'), ('order_payment', 'Order Payment'), ('plant_charge', 'Bottle Delivery Charge'), ('plant_payment', 'Bottle Delivery Payment'), ('payment', 'Payment Received'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive = credit to customer, negative = charge.', max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('item_label', models.CharField(blank=True, help_text="e.g. '19L Refill' or 'Amount Received'.", max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Units delivered on this line.', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('document_number', models.CharField(blank=True, db_index=True, help_text='Bill / voucher number shown on the statement.', max_length=32)),
                ('bottles_out', models.IntegerField(default=0, help_text='Filled bottles handed to the customer.')),
                ('bottles_in', models.IntegerField(default=0, help_text='Empties collected back from the customer.')),
                ('source_ref', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('source_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Bank', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Cheque number / transaction id.', max_length=64)),
                ('receipt_number', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='plant.deliveryrecord')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
                ('reverses', models.OneToOneField(blank=True, help_text='Set on the mirror entry that cancels another out.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='ledger.ledgerentry')),
            ],
            options={
                'verbose_name': 'Ledger entry',
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['customer', 'entry_date'], name='ledger_ledg_custome_59d1b5_idx'), models.Index(fields=['customer', 'entry_type'], name='ledger_ledg_custome_0a16f5_idx'), models.Index(fields=['source_ref'], name='ledger_ledg_source__345aa7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount', 0), _negated=True), models.Q(('bottles_out', 0), _negated=True), models.Q(('bottles_in', 0), _negated=True), _connector='OR'), name='ledger_entry_not_empty'), models.CheckConstraint(condition=models.Q(('order__isnull', True), ('delivery_record__isnull', True), _connector='OR'), name='ledger_single_source')],
            },
        ),
    ]
