# Generated by Django 6.0.1 on 2026-08-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash')], max_length=20),
        ),
    ]
