# Generated by Django 6.0.1 on 2026-08-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ledgerentry_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount included in `amount`; set only on discounted charges.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Line total before discount; set only on discounted charges.', max_digits=14, null=True),
        ),
    ]
