# Generated by Django 6.0.1 on 2026-08-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledgerentry_discount_amount_ledgerentry_gross_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgersettings',
            name='share_location_label',
            field=models.CharField(blank=True, default='', help_text='Default name shown when an admin shares a work-place location. Individual admins can override it on their own profile. Blank uses "<business name> — work place".', max_length=120),
        ),
    ]
