# Generated by Django 6.0.1 on 2026-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ledgersettings_share_location_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgersettings',
            name='payment_account_number',
            field=models.CharField(blank=True, default='', help_text='Account number or IBAN.', max_length=64),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='payment_account_title',
            field=models.CharField(blank=True, default='', help_text="Account holder's name, exactly as the bank shows it — a transfer to a mistyped title bounces.", max_length=120),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='payment_bank_name',
            field=models.CharField(blank=True, default='', help_text='Bank or wallet, e.g. Meezan Bank, JazzCash, Easypaisa.', max_length=120),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='payment_instructions',
            field=models.CharField(blank=True, default='', help_text="Anything the customer must do after paying, e.g. 'Send the receipt screenshot to the rider before he leaves.'", max_length=255),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='QR the customer scans to pay. Optional — the account details alone are enough to take a transfer.', null=True, upload_to='ledger/payment/'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online Transfer')], max_length=20),
        ),
    ]
